### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by kaia-docs**

### CODE REVIEW

**Comment by kaiachain-dev** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kaiachain-dev** [comment]
recheck

**Comment by Sotatek-TinnNguyen** [comment]
recheck

**Comment by Sotatek-TinnNguyen** [comment]
recheck

**Review by scott-klaytn — APPROVED** [review]

**Review by praveen-klaytn — APPROVED** [review]

**Pull request merged**
