### PR TITLE
Fix solidity typo in buy-me-a-coffee tutorial.

### PR DESCRIPTION
**Pull request by kyonRay**
## Proposed changes

Simple typo in buy-me-a-coffee tutorial solidity demo.

## Types of changes

Please put an x in the boxes related to your change.

- [x] Minor Issues and Typos
- [ ] Major Content Contribution
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to reach out. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/kaiachain/kaia-docs/blob/main/CONTRIBUTING.md)
- [x] I have read the [CLA](https://gist.github.com/kaiachain-dev/bbf65cc330275c057463c4c94ce787a6) and signed by comment ```I have read the CLA Document and I hereby sign the CLA``` in first time contribute
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Related issues

Nope

## Further comments

Nope

### CODE REVIEW

**Review by praveen-kaia — APPROVED** [review]

**Comment by praveen-kaia** [comment]
@kyonRay , Thanks for the contribution. Can you please comment "I have read the CLA Document and I hereby sign the CLA" as part of CLA signature. 
Thanks.

**Comment by kyonRay** [comment]
> @kyonRay , Thanks for the contribution. Can you please comment "I have read the CLA Document and I hereby sign the CLA" as part of CLA signature. Thanks.

done

**Comment by ayo-klaytn** [comment]
Hi @kyonRay 

Kindly also comment `I have read the CLA Document and I hereby sign the CLA` in this PR

**Comment by kyonRay** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ayo-klaytn — APPROVED** [review]

**Pull request merged**
