### PR TITLE
update images and doc for foundry to reflect instructions using kaia testnet 

### PR DESCRIPTION
**Pull request by kingzamzon**
## Proposed changes

The current [Deploy Smart Contract Using Foundry](https://docs.kaia.io/build/smart-contracts/deploy/foundry/) section of the docs the images still shows klaytn instead of kaia.

I have created the whole process again, I want to update to the images and link to the smart contract example on Kaia Kairos testnet

- Issue: https://github.com/kaiachain/kaia-docs/issues/160

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Minor Issues and Typos
- [x] Major Content Contribution
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to reach out. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/kaiachain/kaia-docs/blob/main/CONTRIBUTING.md)
- [x] I have read the [CLA](https://gist.github.com/kaiachain-dev/bbf65cc330275c057463c4c94ce787a6) and signed by comment ```I have read the CLA Document and I hereby sign the CLA``` in first time contribute
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large content contribution, kick off the discussion by explaining why you would suggest the content contribution, etc...

### CODE REVIEW

**Comment by ayo-klaytn** [comment]
@kingzamzon thanks for your contribution. 

In the meantime, kindly follow the instructions [here](https://github.com/kaiachain/kaia-docs/pull/161#issuecomment-2516028269) for the check to successfully pass.

**Comment by kingzamzon** [comment]
I just signed the CLA Document but the error still persist. What do you think I do ?

**Comment by ayo-klaytn** [comment]
Kindly comment the statement below in this PR:

I have read the CLA Document and I hereby sign the CLA

Then comment recheck after as stated [here](https://github.com/kaiachain/kaia-docs/pull/161#issuecomment-2516028269)

**Comment by kingzamzon** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kingzamzon** [comment]
recheck

**Review by ayo-klaytn — APPROVED** [review]

**Review by scott-klaytn — APPROVED** [review]

**Pull request merged**
