### PR TITLE
Add Kaiabridge page

### PR DESCRIPTION
**Pull request by blukat29**
## Proposed changes

- Add "Kaiabridge" briefly explaining the FNSA -> KAIA token swap mechanism.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Minor Issues and Typos
- [ ] Major Content Contribution
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to reach out. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/kaiachain/kaia-docs/blob/main/CONTRIBUTING.md)
- [ ] I have read the [CLA](https://gist.github.com/kaiachain-dev/bbf65cc330275c057463c4c94ce787a6) and signed by comment ```I have read the CLA Document and I hereby sign the CLA``` in first time contribute
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large content contribution, kick off the discussion by explaining why you would suggest the content contribution, etc...

### CODE REVIEW

**Comment by blukat29** [comment]
@scott-klaytn @ayo-klaytn Where should this page be placed?

One idea is to reorganize token-related pages

```
token-economy
- kaia-native-token
- kaiabridge
```

but it's up to you on the organization.

**Comment by ayo-klaytn** [comment]
Hi @blukat29 
Two things i ll suggest for the structure.

1. Add to this [section](https://docs.kaia.io/misc/faq-chain-transition/#what-will-happen-to-klay-and-fnsa-) in the Klaytn to Kaia Transition FAQ
2. Rename **Klaytn to Kaia Transition FAQ** to **Transition to Kaia**. 
i. Make the Transition to Kaia a dropdown section with FAQ and KaiaBridge 

What do you say? cc @scott-klaytn

**Comment by scott-klaytn** [comment]
I'd go for ayo's comment because KaiaBridge seems to be a transient system for a specific purpose. Here is my suggestion:

1. Create a folder named "kaia-transition" under "/docs/misc/".
2. Move kaiabridge.md (that is present in /docs/learn/) to /docs/misc/kaia-transition/.
3. Move faq-chain-transition.md (that is present in /docs/misc) to /docs/misc/kaia-transition/.
4. Open faq-chain-transition.md. Change the title from "Klaytn to Kaia Transition FAQ" to "Transition FAQ", delete this very first sentence "The Klaytn blockchain is undergoing a transition to the Kaia blockchain.", and then save the file.
5. Create a md file named "kaia-transition.md" in /docs/misc/kaia-transition/ with the following content:

# Transition to Kaia

The Finschia and Klaytn blockchains are undergoing a transition to the Kaia blockchain. This section provides essential information about the transition process, including frequently asked questions and overview about Kaiabridge, a system designed to facilitate token swaps between the Finschia and Kaia networks.

```mdx-code-block
import DocCardList from '@theme/DocCardList';

<DocCardList />
```

6. Update the `commonSidebar` section in sidebars.js as follows:

```
const commonSidebar = [
  {
    type: 'html',
    value: '<span class="sidebar-divider" />',
  },
  {
    type: 'category',
    label: 'Node Quick Reference',
    link: { type: 'doc', id: 'misc/operation/operation' },
    items: [
      'misc/operation/configuration',
      'misc/operation/node-log',
      'misc/operation/log-management',
      'misc/operation/kaia-command',
      'misc/operation/troubleshooting',
      'misc/operation/chaindata-change',
      'misc/operation/chaindata-migration',
      'misc/operation/upstream-en',
    ],
  },
  //  'misc/klaytn-history',
  'references/public-en',
  {
    type: 'category',
    label: 'Transition to Kaia',
    link: { type: 'doc', id: 'misc/kaia-transition/kaia-transition' },
    items: [
      'misc/kaia-transition/faq-chain-transition',
      'misc/kaia-transition/kaiabridge',
    ],
  },
  'misc/finschia',
  'misc/glossary',
  //'misc/faq',
  'misc/internationalization',
]
```

7. Lastly, update the announcementBar section in docusaurus.config.js as follows:

```
      announcementBar: {
        id: 'docs_archive',
        content: '<div style="font-size: 15px">📢 Kaia docs content is still being updated to reflect the transition from Klaytn and <b>may refer to outdated information until the Mainnnet launch.</b> 🙏🏻 See <b><a target="_blank" href="https://docs.kaia.io/misc/kaia-transition/faq-chain-transition/">Transition FAQ</a></b> first!</div>',
        backgroundColor: '#789806',
        textColor: '#FFFFFF',
        isCloseable: true,
      },
```

@blukat29 Sorry for too many changes imposed on you. 
cc. @ayo-klaytn

**Comment by scott-klaytn** [comment]
Will be submitted again with all the necessary changes included

**Pull request closed without merging**
