### PR TITLE
updates to fee-payer script

### PR DESCRIPTION
**Pull request by FrankiePower**
update to the fee-payer script.

### CODE REVIEW

**Comment by scott-klaytn** [comment]
@FrankiePower Thank you for your contribution. Can you please add a comment "I have read the CLA Document and I hereby sign the CLA" for passing CLA check?

**Comment by FrankiePower** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by FrankiePower** [comment]
recheck

**Comment by FrankiePower** [comment]
recheck

**Comment by scott-klaytn** [comment]
@FrankiePower Can you please try leaving out the period when signing CLA? That is, "I have read the CLA Document and I hereby sign the CLA" instead of "I have read the CLA Document and I hereby sign the CLA."

**Comment by FrankiePower** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by FrankiePower** [comment]
recheck

**Pull request closed without merging**
